version: '3.8'

services:
  arxiv_scraper:
    build: .
    container_name: arxiv_scraper
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1  # 로그 버퍼링 방지, 실시간 기록